[package]
name = "autograder"
version = "0.1.0"
edition = "2021"

[dependencies]
imageproc = "0.25"
image = {version = "0.25", default-features = false, features = [
      "jpeg",
      "png",
      "tiff",
      "pnm",
      "bmp"
]}
nalgebra = "0.33.2"
serde = {version = "1.0.214", features= ["derive"]}
serde_json = "1.0.132"
rayon = "1.10.0"
pdf = "0.9.0"
fax = "0.2.4"
tiff = "0.9.1"
csv = "1.3.0"
clap = {version = "4.5.20", features = ["derive"]}
egui = "0.29.1"
eframe = {version = "0.29.1", default-features = false, features = [
       "default_fonts",
       "glow",
       "persistence"
]}
js-sys = "0.3.72"
wasm-bindgen = "0.2.95"
log = "0.4.22"


[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.45"
web-sys = "0.3.72"
